{% set version = "3.3-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spatstat.geom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.geom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.geom/spatstat.geom_{{ version }}.tar.gz
  sha256: a4ead7bb1f3170983325541fa850506fa2174895a3513590f687856788294683

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-deldir                   # [build_platform != target_platform]
    - r-polyclip                 # [build_platform != target_platform]
    - r-spatstat.data            # [build_platform != target_platform]
    - r-spatstat.univar          # [build_platform != target_platform]
    - r-spatstat.utils           # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-deldir >=1.0_2
    - r-polyclip >=1.10_0
    - r-spatstat.data >=3.1
    - r-spatstat.univar >=3.0_0
    - r-spatstat.utils >=3.1_0
  run:
    - r-base
    - r-deldir >=1.0_2
    - r-polyclip >=1.10_0
    - r-spatstat.data >=3.1
    - r-spatstat.univar >=3.0_0
    - r-spatstat.utils >=3.1_0

test:
  commands:
    - $R -e "library('spatstat.geom')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.geom')\""  # [win]

about:
  home: http://spatstat.org/
  license: GPL-2.0-or-later
  summary: This is a subset of the original 'spatstat' package, containing the user-level code from 'spatstat' which performs geometrical operations, except for the geometry of linear networks.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: spatstat.geom
# Version: 1.65-5
# Date: 2021-01-12
# Title: Geometrical Functionality of the 'spatstat' Package
# Authors@R: c(person("Adrian", "Baddeley", role = c("aut", "cre"), email = "Adrian.Baddeley@curtin.edu.au"), person("Rolf", "Turner", role = "aut", email="r.turner@auckland.ac.nz"), person("Ege",   "Rubak", role = "aut", email = "rubak@math.aau.dk"), person("Tilman", "Davies", role = "ctb"), person("Ute", "Hahn", role = "ctb"), person("Abdollah", "Jalilian", role = "ctb"), person("Suman", "Rakshit", role = "ctb"), person("Dominic", "Schuhmacher", role = "ctb"), person("Rasmus", "Plenge Waagepetersen", role = "ctb"))
# Maintainer: Adrian Baddeley <Adrian.Baddeley@curtin.edu.au>
# Depends: R (>= 3.5.0), spatstat.data (>= 1.6-1), stats, graphics, grDevices, utils, methods
# Imports: spatstat.utils (>= 1.18-0), spatstat.sparse, deldir (>= 0.0-21), polyclip (>= 1.10-0)
# Suggests: spatstat.core, spatstat.linnet, maptools (>= 0.9-9), spatial, fftwtools (>= 0.9-8)
# Description: This is a subset of the original 'spatstat' package, containing the user-level code from 'spatstat' which performs geometrical operations, except for the geometry of linear networks.
# License: GPL (>= 2)
# URL: http://spatstat.org/
# LazyData: true
# NeedsCompilation: yes
# ByteCompile: true
# BugReports: https://github.com/spatstat/spatstat.geom/issues
# Packaged: 2021-01-12 10:41:35 UTC; adrian
# Author: Adrian Baddeley [aut, cre], Rolf Turner [aut], Ege Rubak [aut], Tilman Davies [ctb], Ute Hahn [ctb], Abdollah Jalilian [ctb], Suman Rakshit [ctb], Dominic Schuhmacher [ctb], Rasmus Plenge Waagepetersen [ctb]
# Repository: CRAN
# Date/Publication: 2021-01-15 13:40:06 UTC
