{% set version = "3.3-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spatstat.geom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.geom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.geom/spatstat.geom_{{ version }}.tar.gz
  sha256: 7d0adcac9caf31575fd74639df87b862f0cf5dd7249397499c736d3437104f87

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-deldir                   # [build_platform != target_platform]
    - r-polyclip                 # [build_platform != target_platform]
    - r-spatstat.data            # [build_platform != target_platform]
    - r-spatstat.univar          # [build_platform != target_platform]
    - r-spatstat.utils           # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-deldir >=1.0_2
    - r-polyclip >=1.10_0
    - r-spatstat.data >=3.1
    - r-spatstat.univar >=3.1_0
    - r-spatstat.utils >=3.1_1
  run:
    - r-base
    - r-deldir >=1.0_2
    - r-polyclip >=1.10_0
    - r-spatstat.data >=3.1
    - r-spatstat.univar >=3.1_0
    - r-spatstat.utils >=3.1_1

test:
  commands:
    - $R -e "library('spatstat.geom')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.geom')\""  # [win]

about:
  home: http://spatstat.org/
  dev_url: https://github.com/spatstat/spatstat.geom
  license: GPL-2.0-or-later
  summary: Defines spatial data types and supports geometrical operations
    on them. Data types include point patterns, windows (domains),
    pixel images, line segment patterns, tessellations and hyperframes.
    Capabilities include creation and manipulation of data
    (using command line or graphical interaction),
    plotting, geometrical operations (rotation, shift, rescale,
    affine transformation), convex hull, discretisation and
    pixellation, Dirichlet tessellation, Delaunay triangulation,
    pairwise distances, nearest-neighbour distances,
    distance transform, morphological operations
    (erosion, dilation, closing, opening), quadrat counting,
    geometrical measurement, geometrical covariance,
    colour maps, calculus on spatial domains,
    Gaussian blur, level sets of images, transects of images,
    intersections between objects, minimum distance matching.
    (Excludes spatial data on a network, which are supported by
    the package 'spatstat.linnet'.)
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
